ALTER TABLE "products"
  ADD COLUMN IF NOT EXISTS "colors" JSONB,
  ADD COLUMN IF NOT EXISTS "dimensions" JSONB;

ALTER TABLE "card_items"
  ADD COLUMN IF NOT EXISTS "color" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "dimension" VARCHAR(100);

ALTER TABLE "order_items"
  ADD COLUMN IF NOT EXISTS "color" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "dimension" VARCHAR(100);
